"""Configuration package for fxtele-bot."""

from .constants import FACEBOOK_PARAMS_TO_KEEP
from .settings import (
    HTTP_TIMEOUT,
    USER_AGENT,
    INLINE_CACHE_TIME,
    TELEGRAM_ALLOWED_CHAT_IDS,
    TELEGRAM_ALLOWED_USER_IDS,
    TELEGRAM_ACCESS_STATE_PATH,
    TELEGRAM_MAX_MEDIA_BYTES,
    TELEGRAM_OWNER_ID,
    FACEBOOK_HEADERS,
    REDDIT_HEADERS,
    FACEBOOK_COOKIE_PATH,
    REDDIT_COOKIE_PATH,
)

__all__ = [
    "HTTP_TIMEOUT",
    "USER_AGENT",
    "INLINE_CACHE_TIME",
    "TELEGRAM_ALLOWED_CHAT_IDS",
    "TELEGRAM_ALLOWED_USER_IDS",
    "TELEGRAM_ACCESS_STATE_PATH",
    "TELEGRAM_MAX_MEDIA_BYTES",
    "TELEGRAM_OWNER_ID",
    "FACEBOOK_HEADERS",
    "REDDIT_HEADERS",
    "FACEBOOK_PARAMS_TO_KEEP",
    "FACEBOOK_COOKIE_PATH",
    "REDDIT_COOKIE_PATH",
]
